DERP-225 - Create default paragraph template, create buttons and butt…
GreaterLondonAuthority/accelerator-core-theme pull request #30
Opened 2021-08-16 13:33 UTC by Fullstack-Lincoln

…on drupal templates

2021-08-17 13:43 UTC, philwolstenholme requested changes

2021-08-17 13:43 UTC, philwolstenholme commented on templates/paragraph/paragraph--buttons.html.twig
> +    'u-gap-2',
Swap this for `u-flex-gap-2`

2021-08-17 16:20 UTC, Fullstack-Lincoln commented on templates/paragraph/paragraph--buttons.html.twig
> +    'u-gap-2',
Sorted

2021-08-18 09:35 UTC, philwolstenholme approved these changes

2021-08-18 09:35 UTC, merged